-- ====================================================================
-- 2026년 A101A 단일 블럭 (완전일치) 수배 현장 브랜드별 추출 SQL
-- 작성일자: 2026-09-05
-- 설명: 2026년 수정일 기준 BLOCKNO가 정확히 'A101A'인 BOM 데이터를 추출하며,
--       영업사양(ELV_INFO$VF)의 브랜드(EL_ABRAND), 기종(EL_ATYP), 속도(EL_ASPD), 
--       용량(EL_ACAPA) 및 자재/BOM 정보를 가져옵니다.
-- ====================================================================

WITH ouid AS (
    -- 2026년도 제품(호기) 중 유효 WIP 버전이고, TEST/Q 제외 제품 OID를 추출
    SELECT A.vf$ouid AS VFOID
      FROM HDEL_DEFAULT.product$vf A, HDEL_DEFAULT.product$id B
     WHERE A.vf$identity = B.id$ouid
       AND A.vf$ouid     = B.id$wip
       AND A.MD$NUMBER NOT LIKE 'TEST%'      -- 테스트 호기 제외
       AND A.MD$NUMBER NOT LIKE 'Q%'         -- 견적성 호기 제외
       AND SUBSTR(A.MD$MDATE, 1, 4) = '2026' -- 2026년 수정 제품
)
SELECT 
    -- 1. 제품(호기) 정보
    (SELECT MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF WHERE VF$OUID = PE.PRODUCTOUID) AS PARENTNO,
    (SELECT PRODUCT.MD$STATUS FROM HDEL_DEFAULT.PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_STATUS,
    (SELECT TO_CHAR(TO_DATE(PRODUCT.MD$MDATE,'YYYYMMDDHH24MISS'),'YYYY-MM-DD')
       FROM HDEL_DEFAULT.PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_MODDATE,
       
    -- 2. 영업 사양 정보 (상관 서브쿼리 및 COD 코드 변환)
    (SELECT NVL(HDEL_DEFAULT.COD(E.EL_ABRAND), '기타/미정') FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
      WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
        AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS BRAND,
        
    (SELECT NVL(HDEL_DEFAULT.COD(E.EL_ATYP), '기타') FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
      WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
        AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS GISONG,
        
    (SELECT NVL(HDEL_DEFAULT.COD(E.EL_ASPD), '미지정') FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
      WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
        AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS EL_ASPD,
        
    (SELECT NVL(HDEL_DEFAULT.COD(E.EL_ACAPA), '미지정') FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
      WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
        AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS EL_ACAPA,
        
    (SELECT NVL(HDEL_DEFAULT.COD(E.EL_ASPSCD), '미지정') FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
      WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
        AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS ASPSCD,

    -- 3. 자재(Part) 및 BOM 정보
    NP.MD$NUMBER           AS PARTNO,
    NP.MD$DESC             AS PARTNAME,
    NVL(NP.SPEC, '')       AS SPEC,
    PE.QTY                 AS PART_QTY,
    NVL(PE.CMT, '')        AS CMT,
    
    -- 4. 블록 정보 ('A101A' 완전일치)
    (SELECT B.MD$NUMBER FROM HDEL_DEFAULT.BLOCKNO$SF B
      WHERE B.SF$OUID = TO_NUMBER(UPPER(SUBSTR(NP.BLOCKNO, 12)), 'XXXXXXXX')) AS BLOCKNO
      
  FROM HDEL_DEFAULT.PARTOFEBOM PE
 INNER JOIN HDEL_DEFAULT.NORMALPART$VF NP ON PE.PARTOUID = NP.VF$OUID
  LEFT OUTER JOIN HDEL_DEFAULT.VARIABLEPART_NEW VP
    ON VP.PRODUCTOUID = PE.PRODUCTOUID AND VP.ASSOOUID = PE.ASSOOUID
 WHERE PE.PRODUCTOUID IN (SELECT VFOID FROM ouid)
   AND (SELECT B.MD$NUMBER FROM HDEL_DEFAULT.BLOCKNO$SF B
         WHERE B.SF$OUID = TO_NUMBER(UPPER(SUBSTR(NP.BLOCKNO, 12)), 'XXXXXXXX')) = 'A101A'
