WITH ouid AS (
    SELECT A.vf$ouid AS VFOID
      FROM product$vf A, product$id B
     WHERE A.vf$identity = B.id$ouid
       AND A.vf$ouid     = B.id$wip
       AND A.MD$NUMBER NOT LIKE 'TEST%'
       AND A.MD$NUMBER NOT LIKE 'Q%'
       AND SUBSTR(A.MD$MDATE, 0, 4) = '2026'
       AND A.MD$STATUS = 'RLS'
)
SELECT (SELECT MD$NUMBER FROM PRODUCT$VF WHERE VF$OUID = PE.PRODUCTOUID) AS HOGI_NO,
       (SELECT TO_CHAR(TO_DATE(PRODUCT.MD$MDATE,'YYYYMMDDHH24MISS'),'YYYY-MM-DD')
          FROM PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_MODDATE,
       NVL((SELECT COD(E.EL_ABRAND) FROM ELV_INFO$ID A, ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)), '미지정') AS BRAND,
       (SELECT COD(E.EL_ATYP) FROM ELV_INFO$ID A, ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)) AS GISONG,
       NP.MD$NUMBER AS PARTNO,
       NP.MD$DESC AS PARTNAME,
       PE.QTY AS PART_QTY,
       PE.CMT AS CMT
  FROM PARTOFEBOM PE
 INNER JOIN NORMALPART$VF NP ON PE.PARTOUID = NP.VF$OUID
 WHERE PE.PRODUCTOUID IN (SELECT VFOID FROM ouid)
   AND (SELECT MD$NUMBER FROM BLOCKNO$SF
         WHERE SF$OUID = DECODE(NP.BLOCKNO, NULL, NULL, HEXTODEC(UPPER(SUBSTR(NP.BLOCKNO, 12))))) = 'B181B'
 ORDER BY BRAND, HOGI_NO, PARTNO
