SELECT H.PID,
       H.REG_DATE,
       H.VERSION,
       H.USERID,
       D.*
  FROM HDEL_DEFAULT.VARIANT_D D,
       HDEL_DEFAULT.VARIANT_H H
 WHERE H.VERSION = -1
   AND H.HOUID = D.HOUID
   AND H.PID = 'EL_PB121B'
 ORDER BY D.NO
