-- 2026년에 등록된 전산화 요청 중 김영환 담당 OR 작업(진행/완료 포함) 건 전체 조회
SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS AS STATUS,
    HDEL_DEFAULT.CODN(A.DESIGNPART) AS DESIGNPART,
    A.MD$DESC AS REQ_TITLE,
    A.MD$USER AS REQ_USER_ID,
    U.MD$DESC AS REQ_USER_NAME,
    A.MANAGER AS MANAGER,
    A.HOGI AS HOGI,
    HDEL_DEFAULT.CODN(A.REQUESTTYPE) AS REQ_TYPE,
    HDEL_DEFAULT.CODN(A.REQUESTCAUSE) AS REQ_CAUSE,
    HDEL_DEFAULT.CODN(A.PRIORITY) AS PRIORITY,
    A.REQUESTDETAIL AS REQ_DETAIL,
    A.ANSWERDETAIL AS ANS_DETAIL,
    A.MD$CDATE AS CRE_DATE,
    A.MD$MDATE AS MOD_DATE,
    SUBSTR(A.MD$CDATE, 1, 6) AS CRE_YYYYMM,
    SUBSTR(A.MD$MDATE, 1, 6) AS MOD_YYYYMM
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
LEFT JOIN HDEL_DEFAULT.FUSER$SF U ON A.MD$USER = U.MD$NUMBER
WHERE SUBSTR(A.MD$CDATE, 1, 4) = '2026'
  AND (A.MANAGER LIKE '%김영환%' OR A.ANSWERDETAIL LIKE '%김영환%')
ORDER BY A.MD$CDATE DESC
