SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS,
    A.MD$DESC,
    A.MD$USER,
    A.MANAGER,
    A.HOGI,
    A.REQUESTDETAIL,
    A.ANSWERDETAIL,
    A.MD$CDATE,
    A.MD$MDATE
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
WHERE A.MD$NUMBER LIKE '%4605%'
