-- 2026년동안 김영환 담당 전산화(설계) 요청 건 조회
SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS AS STATUS,
    A.MD$DESC AS TITLE,
    A.MD$USER AS USER_ID,
    (
        SELECT U.MD$DESC
        FROM FUSER$SF U
        WHERE U.MD$NUMBER = A.MD$USER
    ) AS REQUESTER,
    A.MANAGER AS MANAGER,
    A.HOGI AS HOGI,
    HDEL_DEFAULT.CODN(A.PRIORITY) AS PRIORITY,
    HDEL_DEFAULT.CODN(A.DESIGNPART) AS PART,
    HDEL_DEFAULT.CODN(A.REQUESTCAUSE) AS REQ_CAUSE,
    A.REQUESTDETAIL AS REQ_DETAIL,
    A.ANSWERDETAIL AS ANS_DETAIL,
    HDEL_DEFAULT.CODN(A.REQUESTTYPE) AS REQ_TYPE,
    HDEL_DEFAULT.COD(A.ISFINISHDCB) AS DCB_FINISHED,
    HDEL_DEFAULT.COD(A.ISFINISHISIR) AS ISIR_FINISHED,
    HDEL_DEFAULT.COD(A.ISFINISHCERTIFY) AS CERT_FINISHED,
    HDEL_DEFAULT.COD(A.ISHANDLINGSTOCK) AS STOCK_HANDLED,
    HDEL_DEFAULT.DATEFORMAT(A.MD$CDATE, 'YYYYMMDDHH24MISS', 'YYYY-MM-DD HH24:MI:SS') AS CRE_DATE,
    HDEL_DEFAULT.DATEFORMAT(A.MD$MDATE, 'YYYYMMDDHH24MISS', 'YYYY-MM-DD HH24:MI:SS') AS MOD_DATE
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
WHERE A.MANAGER = '김영환'
  AND (SUBSTR(A.MD$CDATE, 1, 4) = '2026' OR SUBSTR(A.MD$MDATE, 1, 4) = '2026')
ORDER BY A.MD$CDATE DESC
