-- 2026년동안 김영환 담당 처리 완료(RLS) 전산화 요청 건 상세 조회
SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS AS STATUS,
    HDEL_DEFAULT.CODN(A.DESIGNPART) AS DESIGNPART,
    A.MD$DESC AS REQ_TITLE,
    A.MD$USER AS REQ_USER_ID,
    U.MD$DESC AS REQ_USER_NAME,
    A.MANAGER AS MANAGER,
    A.HOGI AS HOGI,
    HDEL_DEFAULT.CODN(A.REQUESTTYPE) AS REQ_TYPE,
    HDEL_DEFAULT.CODN(A.REQUESTCAUSE) AS REQ_CAUSE,
    HDEL_DEFAULT.CODN(A.PRIORITY) AS PRIORITY,
    A.REQUESTDETAIL AS REQ_DETAIL,
    A.ANSWERDETAIL AS ANS_DETAIL,
    A.MD$CDATE AS CRE_DATE,
    A.MD$MDATE AS MOD_DATE,
    SUBSTR(A.MD$CDATE, 1, 6) AS CRE_YYYYMM,
    SUBSTR(A.MD$MDATE, 1, 6) AS MOD_YYYYMM
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
LEFT JOIN HDEL_DEFAULT.FUSER$SF U ON A.MD$USER = U.MD$NUMBER
WHERE A.MANAGER = '김영환'
  AND A.MD$STATUS = 'RLS'
  AND (SUBSTR(A.MD$CDATE, 1, 4) = '2026' OR SUBSTR(A.MD$MDATE, 1, 4) = '2026')
ORDER BY A.MD$MDATE DESC, A.MD$CDATE DESC
