-- 금일(2026년 8월 11일) 등록된 비표준 사양검토 요청 내역 조회 SQL
SELECT
    D.MD$NUMBER AS 요청번호,
    D.MD$CDATE AS 등록일,
    HDEL_DEFAULT.CODN(D.STAT) AS 작업상태,
    D.REQTIME AS 의뢰일,
    D.ACPTTIME AS 접수일,
    D.FINTIME AS 완료일,
    HDEL_DEFAULT.CODN(D.DIVISION) AS 등록부서,
    HDEL_DEFAULT.CODN(D.NATION) AS 국내해외,
    D.FILEDNAME AS 현장명,
    D.SUJUNUM AS 호기번호,
    D.PRODUCT_TYPE01 AS 기종,
    HDEL_DEFAULT.CODN(D.PRODUCT_TYPE02) AS 용도,
    HDEL_DEFAULT.CODN(D.WORKSCOPE) AS 작업구분,
    HDEL_DEFAULT.CODN(D.FIRST_TYPE) AS 대분류,
    HDEL_DEFAULT.CODN(D.SECOND_TYPE) AS 중분류,
    D.DUTYTITLE1 AS 제목,
    D.REVIEWTITLE AS 검토요청내용,
    D.DETAIL AS 상세내용,
    D.MANAGER AS 작업담당자,
    D.MEMO AS 회신내용,
    HDEL_DEFAULT.CODN(D.GUBUN) AS 회신구분
FROM HDEL_DEFAULT.dutyreview$sf D
WHERE SUBSTR(D.MD$CDATE, 1, 8) = '20260811'
ORDER BY D.MD$CDATE DESC
