SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS AS STATUS,
    HDEL_DEFAULT.CODN(A.DESIGNPART) AS DESIGNPART,
    A.MD$DESC AS REQ_TITLE,
    A.MD$USER AS REQ_USER_ID,
    U.MD$DESC AS REQ_USER_NAME,
    A.MANAGER AS MANAGER,
    A.HOGI AS HOGI,
    HDEL_DEFAULT.CODN(A.REQUESTTYPE) AS REQ_TYPE,
    HDEL_DEFAULT.CODN(A.REQUESTCAUSE) AS REQ_CAUSE,
    A.REQUESTDETAIL AS REQ_DETAIL,
    A.ANSWERDETAIL AS ANS_DETAIL,
    A.MD$CDATE AS CRE_DATE
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
LEFT JOIN HDEL_DEFAULT.FUSER$SF U ON A.MD$USER = U.MD$NUMBER
WHERE SUBSTR(A.MD$CDATE, 1, 8) = '20260805'
  AND A.DESIGNPART = 2500087253
ORDER BY A.MD$CDATE DESC
