-- 김영환 담당 전산화 요청 건 전체 조회 (조건 테스트)
SELECT
    A.MD$NUMBER AS REQNO,
    A.MD$STATUS AS STATUS,
    A.MD$DESC AS TITLE,
    A.MANAGER AS MANAGER,
    A.MD$CDATE AS CRE_DATE,
    A.MD$MDATE AS MOD_DATE
FROM HDEL_DEFAULT.NEWPLMDESIGNREQUEST$VF A
WHERE A.MANAGER LIKE '%김영환%'
ORDER BY A.MD$CDATE DESC
