SELECT H.PID, H.VERSION, D.NO, NVL(D.ADDR,'-') AS ADDR, NVL(D.GOTO,'-') AS GOTO,
       NVL(D.SPEC1,'-') AS SPEC1, NVL(D.CON1,'-') AS CON1,
       NVL(D.SPEC2,'-') AS SPEC2, NVL(D.CON2,'-') AS CON2,
       NVL(D.SPEC3,'-') AS SPEC3, NVL(D.CON3,'-') AS CON3,
       NVL(D.KEY1,'-') AS KEY1, NVL(D.VAL1,'-') AS VAL1,
       NVL(D.KEY2,'-') AS KEY2, NVL(D.VAL2,'-') AS VAL2,
       NVL(D.REMARKS,'-') AS REMARKS
  FROM HDEL_DEFAULT.VARIANT_D D, HDEL_DEFAULT.VARIANT_H H, HDEL_DEFAULT.VARIANT_ID ID
 WHERE H.HOUID = ID.LAST_HOUID
   AND H.HOUID = D.HOUID
   AND H.PID = 'BOM_E321A'
 ORDER BY D.NO
