WITH ouid AS (
    SELECT A.vf$ouid AS VFOID
      FROM HDEL_DEFAULT.product$vf A, HDEL_DEFAULT.product$id B
     WHERE A.vf$identity = B.id$ouid
       AND A.vf$ouid     = B.id$wip
       AND A.MD$NUMBER NOT LIKE 'TEST%'
       AND A.MD$NUMBER NOT LIKE 'Q%'
       AND A.MD$NUMBER LIKE 'V%'
       AND SUBSTR(A.MD$CDATE, 1, 4) = '2026'
)
SELECT (SELECT MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF WHERE VF$OUID = PE.PRODUCTOUID) AS PARENTNO
     , (SELECT F.VF$VERSION FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID) AS PARENT_VER
     , (SELECT PRODUCT.MD$STATUS FROM HDEL_DEFAULT.PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_STATUS
     , (SELECT CASE WHEN LENGTH(PRODUCT.MD$CDATE) >= 8 
                    THEN SUBSTR(PRODUCT.MD$CDATE, 1, 4) || '-' || SUBSTR(PRODUCT.MD$CDATE, 5, 2) || '-' || SUBSTR(PRODUCT.MD$CDATE, 7, 2)
                    ELSE PRODUCT.MD$CDATE END
          FROM HDEL_DEFAULT.PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_CDATE
     , (SELECT CASE WHEN LENGTH(PRODUCT.MD$MDATE) >= 8 
                    THEN SUBSTR(PRODUCT.MD$MDATE, 1, 4) || '-' || SUBSTR(PRODUCT.MD$MDATE, 5, 2) || '-' || SUBSTR(PRODUCT.MD$MDATE, 7, 2)
                    ELSE PRODUCT.MD$MDATE END
          FROM HDEL_DEFAULT.PRODUCT$VF PRODUCT WHERE PRODUCT.VF$OUID = PE.PRODUCTOUID) AS PROD_MODDATE
     , (SELECT HDEL_DEFAULT.COD(E.EL_ATYP) FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)
           AND ROWNUM = 1) AS GISONG
     , (SELECT HDEL_DEFAULT.COD(E.EL_ABRAND) FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)
           AND ROWNUM = 1) AS BRAND
     , (SELECT HDEL_DEFAULT.COD(E.EL_ASPD) FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)
           AND ROWNUM = 1) AS EL_ASPD
     , (SELECT HDEL_DEFAULT.COD(E.EL_ACAPA) FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)
           AND ROWNUM = 1) AS EL_ACAPA
     , (SELECT HDEL_DEFAULT.COD(E.EL_ASPSCD) FROM HDEL_DEFAULT.ELV_INFO$ID A, HDEL_DEFAULT.ELV_INFO$VF E
         WHERE A.ID$OUID = E.VF$IDENTITY AND E.vf$ouid = A.id$wip
           AND E.MD$NUMBER = (SELECT F.MD$NUMBER FROM HDEL_DEFAULT.PRODUCT$VF F WHERE F.VF$OUID = PE.PRODUCTOUID)
           AND ROWNUM = 1) AS ASPSCD
     , NP.MD$NUMBER  AS PARTNO
     , NP.MD$DESC    AS PARTNAME
     , NP.VF$VERSION AS PART_VERSION
     , NVL(NP.SPEC, '')      AS SPEC
     , NVL(NP.G_L_CODE, '')  AS GLCODE
     , PE.QTY        AS PART_QTY
     , PE.CMT        AS CMT
     , (SELECT B.MD$NUMBER FROM HDEL_DEFAULT.BLOCKNO$SF B
         WHERE B.SF$OUID = DECODE(NP.BLOCKNO, NULL, NULL, TO_NUMBER(UPPER(SUBSTR(NP.BLOCKNO, INSTR(NP.BLOCKNO, '@') + 1)), 'XXXXXXXX'))) AS BLOCKNO
     , (SELECT HDEL_DEFAULT.COD(B.BLOCK_OPT) FROM HDEL_DEFAULT.BLOCKNO$SF B
         WHERE B.SF$OUID = DECODE(NP.BLOCKNO, NULL, NULL, TO_NUMBER(UPPER(SUBSTR(NP.BLOCKNO, INSTR(NP.BLOCKNO, '@') + 1)), 'XXXXXXXX'))) AS BLOCK_OPT
     , VP.UCHECK     AS UCHECK
  FROM HDEL_DEFAULT.PARTOFEBOM PE
 INNER JOIN HDEL_DEFAULT.NORMALPART$VF NP ON PE.PARTOUID = NP.VF$OUID
  LEFT OUTER JOIN HDEL_DEFAULT.VARIABLEPART_NEW VP
    ON VP.PRODUCTOUID = PE.PRODUCTOUID AND VP.ASSOOUID = PE.ASSOOUID
 WHERE PE.PRODUCTOUID IN (SELECT VFOID FROM ouid)
