SELECT 
    V.MD$NUMBER AS PRODUCTNO,
    V.MD$DESC,
    HDEL_DEFAULT.CODN(V.EL_ATYP) AS EL_ATYP,
    HDEL_DEFAULT.CODN(V.EL_AUSE) AS EL_AUSE,
    HDEL_DEFAULT.CODN(V.EL_ABRAND) AS EL_ABRAND,
    HDEL_DEFAULT.CODN(V.EL_ASPD) AS EL_ASPD,
    HDEL_DEFAULT.CODN(V.EL_ACAPA) AS EL_ACAPA,
    V.EL_AMAN AS EL_AMAN,
    V.EL_AFQ,
    HDEL_DEFAULT.COD(V.EL_ASPSCD) AS EL_ASPSCD,
    V.MD$USER,
    V.MD$CDATE,
    V.MANAGER_E,
    V.MANAGER_M
FROM HDEL_DEFAULT.ELV_INFO$VF V,
     HDEL_DEFAULT.ELV_INFO$ID A
WHERE V.vf$identity = A.id$ouid
  AND V.vf$ouid = A.id$wip
  AND V.MD$NUMBER LIKE 'V%'
ORDER BY V.MD$NUMBER
