SELECT 
    A.MD$NUMBER AS PRODUCTNO,
    A.MD$STATUS,
    A.VF$VERSION AS VERSION,
    A.MD$DESC,
    A.MD$USER,
    A.MD$CDATE,
    A.MD$MDATE,
    A.APP_DATE
FROM HDEL_DEFAULT.PRODUCT$VF A,
     HDEL_DEFAULT.PRODUCT$ID B
WHERE A.vf$identity = B.id$ouid
  AND A.vf$ouid = B.id$wip
  AND A.MD$NUMBER LIKE 'V%'
ORDER BY A.MD$NUMBER
