WITH ouid AS (
    SELECT A.vf$ouid AS VFOID, A.MD$NUMBER AS HOGI
      FROM HDEL_DEFAULT.product$vf A, HDEL_DEFAULT.product$id B
     WHERE A.vf$identity = B.id$ouid
       AND A.vf$ouid     = B.id$wip
       AND A.MD$NUMBER NOT LIKE 'TEST%'
       AND A.MD$NUMBER NOT LIKE 'Q%'
       AND SUBSTR(A.MD$MDATE, 1, 4) = '2026'
)
SELECT HDEL_DEFAULT.CODN(EV.EL_ABRAND) AS BRAND,
       COUNT(DISTINCT O.VFOID) AS HOGI_CNT,
       COUNT(*) AS ITEM_CNT
  FROM ouid O
 INNER JOIN HDEL_DEFAULT.PARTOFEBOM PE ON PE.PRODUCTOUID = O.VFOID
 INNER JOIN HDEL_DEFAULT.NORMALPART$VF NP ON PE.PARTOUID = NP.VF$OUID
 INNER JOIN HDEL_DEFAULT.BLOCKNO$SF BLK ON BLK.SF$OUID = TO_NUMBER(SUBSTR(NP.BLOCKNO, 12), 'XXXXXXXXXXXX')
  LEFT OUTER JOIN HDEL_DEFAULT.ELV_INFO$VF EV ON EV.MD$NUMBER = O.HOGI
  LEFT OUTER JOIN HDEL_DEFAULT.ELV_INFO$ID EI ON EI.ID$OUID = EV.VF$IDENTITY AND EV.VF$OUID = EI.ID$WIP
 WHERE BLK.MD$NUMBER = 'B181B'
 GROUP BY HDEL_DEFAULT.CODN(EV.EL_ABRAND)
 ORDER BY HOGI_CNT DESC
